### ISSUE TITLE
Biodiversity for the National Parks (IDA)

### ISSUE THREAD

**Issue by asadmehdi785** [bkhsev/Biodiversity-Capstone-Project-Codecademy#1]
### Criteria 1: Presentation / Analysis Document
* _Score Level:_ 3
* _Comment(s):_ The document is in PDF format. There are slides with data observations using plots created with matplotlib. There are slides for hypothesis testing and corresponding results. While there were overview slides introducing the datasets used, there was a lack of an overarching overview of the objective of the data analysis. In addition, there was a lack of recommendations to be given based on the conclusions found.
 
### Criteria 2: Code Accuracy
* _Score Level:_ 3
* _Comment(s):_ Accurate Python code for every question in the project for the data manipulation with pandas, plots with matplotlib, and hypothesis testing with scipy. Accurate calculation of minimum detectable size, however, the sample size determination is incorrect. It looks like you got 870 for the minimum sample size at the end of the project, however, we are actually looking for an answer around 510 for that. Try going to [this website](https://www.optimizely.com/sample-size-calculator/?conversion=15&effect=33.3&significance=90) and inputting a conversion rate of 15%, minimum detectable effect of 33.3%, and a significance of 90%. That should give you 510 for that part.
 
### Criteria 3: Understanding hypothesis testing and interpreting the p-value
* _Score Level:_ 4
* _Comment(s):_ All steps related to hypothesis testing and interpreting the results were met.
 
### Criteria 4: Ability to interpret the objective & outcome of the analysis in the appropriate context
* _Score Level:_ 2
* _Comment(s):_ While clear objectives were not present in the presentation, the findings were accurately interpreted and clear summaries were given of the results. However, there were no recommendations given in the presentation.
 
### Overall Score: 12/16
Great work with this project! You did a good job making use of the matplotlib, pandas, and scipy libraries from Python in order to complete the required parts of this project. Besides for the issue related to the minimum sample size that I mentioned in the rubric score, there wasn't much that I noticed in terms of the code being inaccurate or anything like that, so well done!

Regarding the presentation, I thought it was excellent overall. The main things that I found it was lacking were statements of clear objectives as well as recommendations based on the results of the analysis. Besides for that though, I think you did a great job introducing the different data sources used, as well as summarizing your findings with the different charts and graphs, all while keeping the descriptive text concise. Nice work with that!

Finally, I just wanted to mention something related to Jupyter Notebooks and how it works with displaying charts and other things. I noticed that you used `print` a lot when inspecting things, for example you used `print species.head()` when first looking at the `species` DataFrame. With Jupyter Notebook, we can instead simply write `species.head()`, and it will give a nicer look of the data. Let me show the difference with an example.

Here we are using `print species.head()`:

![image](https://user-images.githubusercontent.com/16052289/45128800-f96bf480-b14d-11e8-9e51-702541e4bdfc.png)

And here we are just using `species.head()`:

![image](https://user-images.githubusercontent.com/16052289/45128807-07217a00-b14e-11e8-93da-262f13da7f90.png)

In my opinion, the second representation can be easier to read, especially for more complicated DataFrames. Also, simply writing the name of the variable instead of putting `print` behind it can result in some minor differences, but I think it makes the biggest difference when trying to look at things like DataFrames.

Great job overall! I hope you enjoyed the course!

**Comment by bkhsev** [comment]
Regarding the "Code Accuracy" criterion. The Sample Size Calculator provided in Project's Jupyter Notebook was different from the one provided in the link above. 

I contacted the support and clarified the issue, so the sample size calculated by me is correct. 

Thanks for the review! :)
